### PR TITLE
findUserComments should sort by CreatedAt

### PR DESCRIPTION
**Pull request by pbrisbin**
Whoops...

### CODE REVIEW

**Comment by jferris** [comment]
But it compiled!!!

Should we have any tests for this change?

**Comment by pbrisbin** [comment]
This is very strange. In trying to add a test, I'm finding that I can't make it fail.

```
runDB $ selectList [] []
```

Seems to naturally sort by Created.

**Comment by pbrisbin** [comment]
And yet, this is returning comments out of order: https://carnival-staging.herokuapp.com/sites/2/comments?article=announcing-maintaining-open-source-projects-book

**Comment by pbrisbin** [comment]
I'm done figuring this out, it has to be something about my Postgres setup. I'm just going to add the test even though I can't make it fail.

**Comment by pbrisbin** [comment]
@jferris is this OK to merge?

**Pull request merged**
