### PR TITLE
Add styles for plans page

### PR DESCRIPTION
**Pull request by smharley**
image

### CODE REVIEW

**Comment by jferris** [comment]
Looks good!

I think we should get some feedback from @thoughtbot/design on the CSS and visuals.

**Comment by smharley** [comment]
Agreed! Just pushed up a couple fixes for the stripe button, will get feedback shortly :racehorse:

**Comment by kylefiedler** [comment]
Why is the call to action for enterprise in a different spot than the other plans? Should we play down the free version more?

Code looks good.

**Comment by smharley** [comment]
@kylefiedler mostly because there isn't a price, you have to contact us for both pricing and subscribing. Do you think it would be better to have "Contact us" in both locations? Something else?

**Comment by donokuda** [comment]
@jferris Are comments limited for Business and Personal plans? I see "Unlimited Comments" in the enterprise section but no mention about limited comments elsewhere.

**Comment by kylefiedler** [comment]
@smharley What about `Prices Vary` and have the button at the bottom say `Contact us for Pricing`? It just feels less important compared to the others where as I would assume it's second most important.

**Comment by ldamon** [comment]
Does "no branding" mean "you can use your own branding"?
If so, I might say, "no carnival branding" or "your own branding" or "customized styling".

**Comment by smharley** [comment]
:+1: good feedback everyone, thanks!

**Comment by jferris** [comment]
> Are comments limited for Business and Personal plans?

No, not right now. We talked about doing that, but we didn't apply comment quotas for the initial release.

**Comment by smharley** [comment]
Updated design: @donokuda @kylefiedler 
image

**Comment by donokuda** [comment]
LGTM

**Pull request merged**
