### PR TITLE
Change thoughtbot references to use https

### PR DESCRIPTION
**Pull request by jferris**
* We now support https for the blog
* We have an SSL endpoint for this app on Heroku
* We have a wildcard cert for thoughtbot.com subdomains
* We need to serve https references to avoid unsafe warnings

### CODE REVIEW

**Comment by mike-burns** [comment]
Can some of these values be pulled out into a setting or, in general, a shared variable?

**Comment by pbrisbin** [comment]
I'd rather save that to do as part #105 (e.g. extract a `Site` model and make thoughtbot just the first record).

**Comment by jferris** [comment]
I agree with @pbrisbin about the `Site` model.

**Comment by jferris** [comment]
Good to merge?

**Comment by pbrisbin** [comment]
I think so.

**Pull request merged**
