### PR TITLE
Style login page #220

### PR DESCRIPTION
**Pull request by smharley**
* Change sign in link to point to /auth/login
* Make language consistent: Sign in/Sign out

image

### CODE REVIEW

**Comment by pbrisbin** [comment]
This looks great.

There are two other Sign in links: the Homepage and the Embed template. Do you want to change those here too, or follow up separately? I don't mind either way.

**Comment by donokuda** [comment]
Markup looks good to me. :+1:

**Comment by smharley** [comment]
I'll change the links, and get them in here

**Comment by smharley** [comment]
image

**Comment by smharley** [comment]
@pbrisbin can I get a review of the new links?

**Comment by pbrisbin** [comment]
LGTM

**Pull request merged**
