### PR TITLE
Re-introduce openRequest duplication

### PR DESCRIPTION
**Pull request by pbrisbin**
As part of af142f2, the request building logic was centralized. Something
about this refactor breaks CORS requests entirely.

This commit reverts that, and introduces the Firefox fix without removing the
duplication, which we will address separately.

### CODE REVIEW

**Comment by gabebw** [comment]
Is this a pure `git revert af142f2`?

**Comment by pbrisbin** [comment]
> This commit reverts that, and introduces the Firefox fix without removing the
duplication

**Comment by gabebw** [comment]
I'll take that as a "no".

Have you confirmed this works on, say, the staging blog? Or is the idea to merge this and apply another fix if it doesn't work?

**Comment by pbrisbin** [comment]
I've confirmed this works locally. Next step is staging blog, I usually merge before testing there rather than deploying a branch.

**Comment by gabebw** [comment]
Reasonable. Merge away.

**Pull request merged**
